server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://database-1.c9v46leqnkb2.ap-northeast-2.rds.amazonaws.com:3306/promisorDB-dev?serverTimezone=Asia/Seoul
    username: admin
    password: Kershaw22!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        default_batch_fetch_size: 500
        format_sql: true
    open-in-view: false

  mail:
    host: localhost
    port: 1025
    username: adminTest
    password: test
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
security:
  kakao:
    apikey: 2a4dfce9ea2dadb607b872ae4a973922
  jwt:
    token:
      secret-key: sd92dfs0-1544-32da-bd21-bd234slkj
      expire-length: 36000000
      expire-length-refresh: 5184000000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: desc